config/routes.rb
Rails.application.routes.draw do
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def create
        Question.create(
            body: params[:question][:body],
            user_id: params[:question][:user_id]
        )
    end

    def update
        @question = Question.find(params[:id])
        @question.update(
            body: params[:question][:body],
            user_id: params[:question][:user_id]
        )
    end
    def destroy
        @question = Question.find(params[:id])
        @question.destroy
    end

    def show
        @question = Question.find(params[:id])
    end

    def index
        @questions = Question.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsBranco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/create.html.erb
Вы создали

app/views/questions/destroy.html.erb
Вы удалили

app/views/questions/index.html.erb
<% @questions.each do |question|%>
    <p> <%= link_to "id = #{question.id}", questions_path(id: question.id) %></p>
    <p>question = <%= question.body%></p>
    <p>user_id = <%= question.user_id%></p>
<%end%>

app/views/questions/show.html.erb
<p>id = <%= @question.id%></p>
<p>question = <%= @question.body%></p>
<p>user_id = <%= @question.user_id%></p>

app/views/questions/update.html.erb
Вы обновили